{{- $fullname := include "app.fullname" . }}

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.environment }}-{{ $fullname }}-hpa
  labels:
    app: {{ .Values.environment }}-{{ $fullname }}-hpa
spec:
  scaleTargetRef:
    kind: Deployment
    name: {{ .Values.environment }}-{{ $fullname }}
  minReplicas: {{ .Values.pod.replicas }}
  maxReplicas: {{ .Values.pod.scaling.maxReplicas | default 10 }}
  metrics:
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 70
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 70